[build-system]
requires = ["scikit-build-core>=0.8.0", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "mmm"
version = "0.0.1"
description = "Multitrack Music Machine (native C++ core)."
authors = [
    { name = "Paul Triana", email="paul_triana@sfu.ca"}
]
readme = "pylib/README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers", 
    "Intended Audience :: Science/Research", 
    "Topic :: Scientific/Engineering :: Artificial Intelligence", 
    "Topic :: Multimedia :: Sound/Audio :: MIDI", 
    "License :: OSI Approved :: MIT License",
    "Programming Language :: C++",
    "Programming Language :: Python", 
    "Programming Language :: Python :: 3.8", 
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10", 
    "Programming Language :: Python :: 3.11", 
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
urls = { Homepage = "https://github.com/Metacreation-Lab/MMM" }

[tool.scikit-build.cmake.define]
CMAKE_BUILD_TYPE = "Release"
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
BUILD_PYBIND = "ON"
BUILD_BENCHMARK = "OFF"
USE_ONNX = "ON"
USE_TORCH = "OFF"
APPLY_LIBTOK_PATCH = "ON"

[tool.scikit-build]
wheel.packages = ["mmm"]
build-dir = "build"
wheel.expand-macos-universal-tags = true
cmake.version = ">=3.10"
build.verbose = true
logging.level = "INFO"