[build-system]
requires = ["scikit-build-core>=0.8.0", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "mmm"
version = "0.0.1"
description = "Multitrack Music Machine (native C++ core)."
authors = [
    { name = "Paul Triana" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers", 
    "Intended Audience :: Science/Research", 
    "Topic :: Scientific/Engineering :: Artificial Intelligence", 
    "Topic :: Multimedia :: Sound/Audio :: MIDI", 
    "License :: OSI Approved :: MIT License",
    "Programming Language :: C++",
    "Programming Language :: Python", 
    "Programming Language :: Python :: 3.8", 
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10", 
    "Programming Language :: Python :: 3.11", 
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
urls = { Homepage = "https://github.com/Metacreation-Lab/MMM" }

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
cmake.verbose = true
cmake.minimum-version = "3.10"

wheel.packages = ["mmm"]

wheel.include = [
    "mmm/onnxruntime/**",
    "mmm/torch/**"
]

[tool.scikit-build.cmake.define]
CMAKE_BUILD_TYPE = "Release"
BUILD_PYBIND = "ON"
BUILD_BENCHMARK = "ON"
USE_ONNX = "ON"
USE_TORCH = "OFF"

[tool.scikit-build]
build-dir = "build"